version: '3.3'
services:
  app:
    container_name: E-commerce_backend
    build: ./back-end
    ports:
      - "8091:8091"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce_multi
  web:
    build: ./front-end
    image: ecommerce_frontend
    ports:
      - "62250:80"
    depends_on:
      - app